### ISSUE TITLE
Under development ?

### ISSUE THREAD

**Issue by bderenzo** [bacardi55/pimaton#1]
Is this application still under development ?
Will the hardware button with GPIO be added ?

thanks in advance,
bderenzo

**Comment by bacardi55** [comment]
Hi,

Yes - it is still planned. I need to have this fully ready in August for a wedding so i'll finish it, including the GPIO hardware button (I already bought it as well as a light to manage a flash when taking picture)

I had a lot of work recently and couldn't spend any free time on it in March at all, but I plan to restart it in the coming weeks… I don't know how urgent is your need though but it is definitely still alive!

Thanks for your interest tough (:

**Comment by bderenzo** [comment]
Hi,

Thanks for the reply. I just want to know because want to try it and using for a wedding in 2019.
It's not urgent at all :) I don't know python but I will try to help if I find time. 
I close the issue (as is not one).

bderenzo

**Comment by bacardi55** [comment]
I've started implementing the GPIO start button.

It requires a weird workaround and I would love some tests :)

[More info here](https://github.com/bacardi55/pimaton/issues/7#issuecomment-387886710)
