### ISSUE TITLE
Allow different image format like png

### ISSUE THREAD

**Issue by bacardi55** [bacardi55/pimaton#11]

**Comment by bacardi55** [comment]
This has been implemented in the master branch in commits 
https://github.com/bacardi55/pimaton/commit/83d83b7029f63c665f452ff849b75d90af047ab8 and https://github.com/bacardi55/pimaton/commit/9cb60a31848b22c79cdd4194e78103c2be23907d

More info:
https://git.bacardi55.org/bacardi55/pimaton/issues/46
https://git.bacardi55.org/bacardi55/pimaton/issues/42

**Comment by ukoofred** [comment]
👍
