### ISSUE TITLE
GPIO inclusion

### ISSUE THREAD

**Issue by ukoofred** [bacardi55/pimaton#3]
Bonjour !
Quelques ressources contenant le nécessaire pour la partie GPIO 😀 

- Idéalement prévoir un bouton pour lancer l'opération au lieu d'un clic (permet usage écran basique plus grand format ou récup #VGAquitraineàlacave
- Imprimer le qr code envoyant vers la photo partageable sur différents réseaux sociaux (dev en cours d'une app) par l'utilisateur à l'aide de son smartphone.

##Ajout/install biblio GPIO
$ sudo apt-get install python-rpi.gpio python3-rpi.gpio

##exemple activation et script
import RPi.GPIO as GPIO # Import Raspberry Pi GPIO library
GPIO.setwarnings(False) # Ignorer les warning pour le moment
GPIO.setmode(GPIO.BOARD) # Utiliser les ports physiques de la carte GPIO
GPIO.setup(10, GPIO.IN, pull_up_down=GPIO.PUD_DOWN) # Utiliser pin 10 (exemple) pour etre un pin de capture et mettre en etat initial à off

##exemple script "Push.py"
while True: # Run forever
    if GPIO.input(10) == GPIO.HIGH:
        print("Quelqu'un a touché au bouton !")

Ps: désolé, Noob sur Python & RasPi, peu d'usage de GIT et beaucoup de mauvaises habitudes ;-)

Je vais avancer de mon coté pour soumettre des commentaires de codes ou un peu plus de doc une fois installé et testé/analysé

**Comment by bacardi55** [comment]
Hello,

(switching to english as most people on github don't speak French :)).
Thanks for all this, I plan to work again on Pimaton this week end and mostly finish the GPIO integration (hardware button + Light / flash) it the week of the 8th of May.

Thanks for the snippet too, will help go faster 

So stay tuned and thanks for your interest in Pimaton :)

**Comment by bacardi55** [comment]
I've started implementing the GPIO start button.

It requires a weird workaround and I would love some tests :)

[More info here](https://github.com/bacardi55/pimaton/issues/7#issuecomment-387886710)
