### ISSUE TITLE
 An error occured: can't invoke "pack" command

### ISSUE THREAD

**Issue by ukoofred** [bacardi55/pimaton#4]
Hi !
During tests i have some errors below : 

I have complete reinstall by pip and maybe have a trouble in version ?
All seems Ok during install : 

> Successfully installed pimaton-0.0.4 pycups-1.9.73 pyyaml-3.12 qrcode-6.0
I run  : 
pimaton --config-file=/home/pi/pimaton/config.yaml --single

It display V0.0.2 : 

> 2018-05-05 12:45:40 :: Pimaton-0.0.2 :: *** Welcome to pimaton! ***
> 2018-05-05 12:45:40 :: Pimaton-0.0.2 :: *** Pimaton is loading... ***
> 2018-05-05 12:45:40 :: Pimaton-0.0.2 :: *** Configuring Pimaton ***
> 2018-05-05 12:45:41 :: Pimaton-0.0.2 :: **** Pimaton is configured to NOT print image.
> 2018-05-05 12:45:41 :: Pimaton-0.0.2 :: *** Loading UI... ***
> 2018-05-05 12:45:41 :: Pimaton-0.0.2 :: *** Loading Graphical UI... ***
> 2018-05-05 12:45:42 :: Pimaton-0.0.2 :: *** Pimaton GUI *** Single Loop is True, not waiting for trigger!
> 2018-05-05 12:45:44 :: Pimaton-0.0.2 :: *** Pimaton *** Starting taking pictures
> 2018-05-05 12:46:01 :: Pimaton-0.0.2 :: *** Pimaton *** Starting image generation
> 2018-05-05 12:46:01 :: Pimaton-0.0.2 :: Template file given doesnt exists, creating empty image
> 2018-05-05 12:46:02 :: Pimaton-0.0.2 :: *** Pimaton Image *** Final picture has been generated
> 2018-05-05 12:46:08 :: Pimaton-0.0.2 :: *** Pimaton GUI *** Single Loop is True, exiting Pimaton
> 2018-05-05 12:46:10 :: Pimaton-0.0.2 :: An error occured: can't invoke "pack" command: application has been destroyed.

**Comment by bacardi55** [comment]
Hi, 

Seems that you are using the --single option which makes the program stop after the 1st usage. You can see this in logs : 

```
*** Pimaton GUI *** Single Loop is True, exiting Pimaton
```

The error at the end is not really an error it is because the UI is killed after 1st loop.

It should have taken your pictures and generate the picture. Based on your log, without a template and without trying to print the final pic.

Let me know if you have issues

**Comment by ukoofred** [comment]
Ok, well, it seems ok on standard mode.
My config file is set to NOT print.
I don't have set a template file, that's a point i will correct.

For the :: Pimaton-0.0.2 :: version, i mean it's just an missed update of some infos files on pip ?

**Comment by bacardi55** [comment]
The 0-2 in logs is just a mistake on my part. I'll fix it next week when i'll work on it again to implement the GPIO options.

What i'm not sure from your message is : did it work ? Did u manage to get the finale picture being generated (even on an empty template) or do you have issue making it work ?

If.you need helo regarding your config, feel free to paste it too :)

**Comment by ukoofred** [comment]
It finally works.
I will open other issues based on some improvments i can suggest.
