### ISSUE TITLE
Error: Out of Resources When Trying to Run GUI Version

### ISSUE THREAD

**Issue by rwmccoy** [bacardi55/pimaton#8]
I got pimaton working in text mode but had problems when attempting GUI mode. Here is my command and output: 
`pi@raspberrypi:~ $ pimaton --config-file ~/default_config.yaml
2018-05-05 20:09:14 :: Pimaton-0.0.2 :: *** Welcome to pimaton! ***
2018-05-05 20:09:14 :: Pimaton-0.0.2 :: *** Pimaton is loading... ***
2018-05-05 20:09:14 :: Pimaton-0.0.2 :: *** Configuring Pimaton ***
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x18c9860 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
2018-05-05 20:09:15 :: Pimaton-0.0.2 :: An error occured: Failed to enable connection: Out of resources
pi@raspberrypi:~ $ `

I had a problem with release 10 of Pip and had to change the import statement in Pip:
from: from pip import main
to: from pip._internal import main

Other than that, I had no problems with installation. 

Any pointers on how I should debug or do you have a fix?

Thanks.

**Comment by rwmccoy** [comment]
I increased GPU memory from 64 to 256 and returned the image size to the default. 
The error changed. Now I get:
`2018-05-05 21:38:37 :: Pimaton-0.0.2 :: An error occured: 'NoneType' object has no attribute 'mainloop'`

**Comment by ukoofred** [comment]
It's seems be a camera problem, can you give the model used ?

**Comment by rwmccoy** [comment]
It's on a Raspberry 3B using a version 2 camera but...

It was an error on my part in the yaml file. I haven't tracked it down yet but starting with the default_full yaml instead of my modified default_yaml cleared the problem. 

Sorry for the noise.
